(function(e){var k=window.AmazonUIPageJS||window.P,f=k._namespace||k.attributeErrors,b=f?f("CustomerReviewsCommonAssets",""):k;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,k,f){e.when("A","cr-log-utils","cr-uri-utils","cr-streaming-utils").register("cr-ajax-model",function(b,d,a,c){function g(n){var b=a.getUrlParametersMap()||{};b["overrides-marketplace-id"]&&(n=a.addKeyValuePair(n,"overrides-marketplace-id",b["overrides-marketplace-id"]));return n}function p(n){l[n]&&
(l[n].abort(),delete l[n])}function q(n,a,t,e,f,r,u,v){a=a||{};a.params=a.params||{};var y;y=r?r:m=m++;r=y;f=f?f:a.error||function(){};e=e?e:0;t=t?t:2;v=v?v:"FATAL";var A="FATAL"===v?0:1,x=a.finallyCallback||function(){};n=g(n);u||(u="reviewsAjax"+h++,k.uet&&k.uet("tc",u));a.params.scope=u;a.contentType="application/x-www-form-urlencoded;charset\x3dUTF-8";var z=a.success||function(){};a.success=function(a){delete l[r];"function"===typeof z&&z(a);"function"===typeof x&&x(a)};a.error=function(b,c,g){p(r);
b=b||{};var h=(b.http||{}).status||"[]";e++;e<t?(c="AJAX Post to "+n+" from "+k.location.href+" failed, status code passed through parameter was: "+c+", status code extracted from XHR HTTP object was: "+h+", attempt "+e+" of "+t+", error message was: \n "+g,d.logError(c,"WARN"),q(n,a,t,e,f,r,u)):(c="AJAX Post to "+n+" from "+k.location.href+" failed, status code passed through parameter was: "+c+", status code extracted from XHR HTTP object was: "+h+", exhausted "+t+" attempt(s), error message was: \n "+
g,d.logError(c,v),d.logCount("AjaxFailureFatal",A),"function"===typeof f&&f(b),"function"===typeof x&&x(b))};"function"!==typeof a.chunk&&(a.chunk=function(a){"appendFadeIn"===a[0]?c.appendFadeIn(a):"replace"===a[0]&&c.replace(a)});l[r]=b.post(n,a);return r}var h=0,m=1,l={};return{abort:p,post:q,postWithoutFatals:function(a,b,c,p,g,h,d){return q(a,b,c,p,g,h,d,"WARN")}}});"use strict";e.when("A","cr-jQuery","cr-log-utils","cr-number-utils").register("cr-A",function(b,d,a,c){b.getListFromState=function(a){var c=
b.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return b.reduce(c,function(b,c){c!==f&&c[a]!==f&&b.push(c[a]);return b},[])};b.getValueFromState=function(c){var g=b.getListFromState(c);1<g.length&&a.logError("More than one  value defined for key: "+c,"ERROR");return g[0]};var g={top:-100,left:-100};b.inView=function(a){a=a||d();if("function"===typeof a.offset){var c=(a.offset()||g).top-d(k).scrollTop();a=0<=c;c=c<d(k).height();return a&&c}return!1};b.onScreenAndVisible=
function(a,b){a=a||d();b=c.isFiniteNumber(b)?b:0;if(a instanceof d||a.jquery){if(!a.is(":visible"))return!1;a=a[0].getBoundingClientRect();return a.top>=0-b&&a.left>=0-b&&a.bottom<=d(k).height()+b&&a.right<=d(k).width()+b}return!1};b.compositeEventWrapper=function(c,g,d){var m=c;d&&(m=b.throttle(m,d,{trailing:!1}));return a.jsGuard(function(a){a&&(m(a),g&&a.$event&&a.$event.preventDefault())})};b.freeze=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):
a};b.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return b});"use strict";e.when("jQuery").register("cr-jQuery",function(b){return b});"use strict";e.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},
events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",
SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",
FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",
SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",
THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});"use strict";e.when("A","cr-string-utils",
"cr-log-utils").register("cr-popup",function(b,d,a){function c(c){var p={};c&&c.data&&(p=c.data);var e=d.defaultIfBlank(p.url,c.$target.find("a").andSelf().filter("a").attr("href")),h=d.defaultIfBlank(p.title,"CustomerReviews"),h=""+h,m="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,c){a=d.defaultIfBlank(p[c],a);m+=c+"\x3d"+a+","});var m=m.slice(0,-1),l=null;try{(l=k.open(e,h,m))?l.focus():a.logError("Unable to move focus to popup window with data: "+
d.stringify(p),"ERROR"),c.$event.preventDefault()}catch(n){a.logError("Unable to open window with parameters: "+d.stringify(p),"FATAL",n)}return l}b.declarative("cr-popup",["click"],a.jsGuard(c));return{popup:c}});"use strict";e.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view").register("cr-generic-declarative-actions",function(b,d,a,c,g,p){function e(a){l(a)&&a.data.selector&&a.data.cssClass&&(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),
b.trigger("a:pageUpdate"))}function h(a){l(a)&&a.data.scrollToSelector&&(p.scrollTo(a.data.scrollToSelector,0),a.$event.preventDefault())}function m(a){if(l(a)&&a.data.url&&a.data.params){a.$event.preventDefault();b.declarative.remove(a.$currentTarget,w.AJAX_POST);a=a.data;var g=a.params,h=d(a.indicatorSelector)[0],e=n(d.fn.hide,a.hideOnSuccessSelector),p=n(d.fn.show,a.showOnFailureSelector);d(a.removeOnLoadSelector).remove();c.post(a.url,{params:g,indicator:h,success:e,error:p})}}function l(a){return a&&
a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function n(a,c){if(c&&"function"===typeof a)return function(){var b=d(c);0<b.length&&a.call(b)}}var w=a.events;b.declarative(w.TOGGLE_CLASS_CLICK,"click",e);b.declarative(w.SCROLL_TO_ELEMENT_CLICK,"click",h);b.declarative(w.AJAX_POST,"click",m);return{toggleCssClass:e,scrollToElement:h,ajaxPost:m}});"use strict";e.register("cr-global-model",function(){return{generateUrl:function(b,d){b&&"/"!==b.charAt(b.length-1)&&(b+="/");b&&d&&(b=b+"ref\x3d"+
d);return b}}});"use strict";e.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,d,a,c,g){function e(a){var c="";if(a&&a.closest!==f){var b=a.closest("*["+l.REFTAG+"]");b&&(c=b.attr(l.REFTAG))}g.isBlank(c)&&a&&a.closest!==f&&(a=a.closest("*[rel]"))&&(c=a.attr("rel"));return g.defaultIfBlank(c,"cm_cr_unknown")}function q(a){return a&&"function"===typeof a.is?a.is("*["+l.getReviews.CHECKED+"]")&&a.is("*["+l.getReviews.UNCHECKED+"]"):!1}function h(a){return a&&
a.has!==f&&a.is!==f?0<a.find(":checked").length||a.is(":checked"):!1}function m(a,c){return a&&a.attr!==f&&c?g.parseJSON(a.attr(c))||{}:{}}var l=c.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){a!==f&&a.expander!==f&&a.expander.$expander!==f&&1===a.expander.$expander.length&&a.expander.$expander[0].closest(".review")!==f&&a.expander.$expander[0].closest(".review").offsetTop!==f&&(a=a.expander.$expander[0].closest(".review").offsetTop,k.scroll(0,a))});b.on("a:pageUpdate",
function(){d!==f&&d.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(l.getReviews,function(a,c){return a+"*["+c+"],"},"").slice(0,-1),d;c&&a&&a.closest!==f&&(d=a.closest(c));return q(d)?h(d)?m(d,l.getReviews.CHECKED):m(d,l.getReviews.UNCHECKED):m(d,l.getReviews.STANDARD)},getReftag:function(c){var b;c&&c.$target&&(b=c.$target);c&&c.id&&(b=a("#"+c.id));c&&c.expander&&c.expander.$expander&&(b=c.expander.$expander);b=e(b);"cm_cr_unknown"===b&&c&&c.data&&c.data.reftag&&
(b=c.data.reftag);return b},getReftagByDom:e,scrollTo:function(c,b){c=a(c).offset();b=b||0;var d=a("#cr-state-object").data("state"),d=d!==f&&d.disableScroll;c&&c.top!==f&&!d&&(a("html,body").stop(),a("html,body").animate({scrollTop:c.top-b},{queue:!1,duration:500}))}}});"use strict";e.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","ready").register("cr-lazy-widget-controller",function(b,d,a,c,g,e){function f(b){a.loadLazyWidgets(c.getLazyWidgetStubs())&&
g.logCount("LazyWidgetTrigger:"+b,1)}var h={};h.bufferPixels=e.convertToInteger(b.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);h.delayBeforeTriggering=e.convertToInteger(b.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);h.triggerLazyLoadIfWidgetWithinBuffer=function(g){a.lazyLoadHasTriggered()||c.getLazyWidgetStubs().each(function(a,c){if(b.onScreen(d(c),h.bufferPixels))return f("scroll"),b.off("scroll",h.triggerLazyLoadIfWidgetWithinBuffer),!1})};var m={};h.logVisibleStubMetrics=
function(a){c.getLazyWidgetStubs().each(function(a,c){a=d(c);c=a.data("widget-name");!m[c]&&b.onScreen(a)&&(g.logCount("VisibleLazyWidgetStub",1),g.logCount("VisibleLazyWidgetStub:"+c,1),m[c]=!0)})};b.on("scroll",h.logVisibleStubMetrics);b.on("scroll",h.triggerLazyLoadIfWidgetWithinBuffer);d(c.getHoverTargets()).mouseenter(function(){f("hover")});return b.freeze(h)});"use strict";e.when("cr-A","cr-ajax-model","ready").register("cr-lazy-widget-model",function(b,d){var a={},c=b.getValueFromState("lazyWidgetLoaderUrl"),
g=!1;a.loadLazyWidgets=function(a){if(!g&&0<a.length){g=!0;var e=b.getValueFromState("asin"),h=b.getValueFromState("lazyWidgetCsrfToken");a=b.reduce(a,function(a,c){return a+"\x26lazyWidget\x3d"+b.$(c).data("widget-name")},c+"?asin\x3d"+e+"\x26csrf\x3d"+h);d.postWithoutFatals(a,{cache:!1,headers:{"cache-control":"no-cache"}});return!0}return!1};a.lazyLoadHasTriggered=function(){return g};return b.freeze(a)});"use strict";e.when("cr-A","cr-jQuery","ready").register("cr-lazy-widget-view",function(b,
d){var a={},c=b.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";a.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};a.getHoverTargets=function(){d(c)};return b.freeze(a)});"use strict";e.when("A").register("cr-log-utils",function(b){function d(a,b,d){k.ueLogError&&("string"!==typeof b&&(b="FATAL"),d?k.ueLogError(d,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):k.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function a(a,
b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:d,jsGuard:function(a){if("function"===typeof a)return function(){try{return a.apply(this,arguments)}catch(b){d("Uncaught Error in function","FATAL",b)}};d("Unable to wrap non-function","ERROR");return a},incrementCount:function(c,b){k.ue&&(c=a(c,b),b=k.ue.count(c)||0,k.ue.count(c,b+1))},logCount:function(c,b,d){k.ue&&(c=a(c,d),k.ue.count(c,b))}}});"use strict";e.register("cr-mash-utils",function(){var b=!1;e.when("mash").execute(function(){b=
!0});return{isMash:function(){return b}}});"use strict";e.when("A","cr-log-utils").register("cr-number-utils",function(b,d){return{convertToInteger:function(a,c){if(a===parseInt(a,10))return a;if(null!==a&&a!==f&&""!==a)return parseInt(a.replace(/[^0-9]/g,""),10);if(c!==f)return c;d.logError("convertToInteger","Cannot convert "+a+" to Integer");return 0},isFiniteNumber:function(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}}});"use strict";e.when("A","cr-jQuery").register("cr-streaming-utils",
function(b,d){return{appendFadeIn:function(a){if(null!==a&&2<a.length&&null!==a[1]&&null!==a[2]){var c=a[1];a=d(a[2]).hide();d(c).append(a);b.fadeIn(a,500,"ease-in-out",function(){})}},replace:function(a){if(null!==a&&2<a.length&&null!==a[1]&&null!==a[2]){var c=a[2];d(a[1]).replaceWith(d(c))}}}});"use strict";e.when("A","cr-log-utils").register("cr-string-utils",function(b,d){function a(a){return null===a||a===f?!0:0===b.trim(a).length}return{defaultIfBlank:function(c,b){return a(c)?b:c},isBlank:a,
parseJSON:function(a){try{return b.parseJSON(a)}catch(g){d.logError("Unable to parse JSON object","ERROR",g)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return k.JSON&&k.JSON.stringify?k.JSON.stringify(a):a}}});"use strict";e.when("A").register("cr-uri-utils",function(b){function d(a){a=a||k.location.href;var c={},d=a.indexOf("?"),e=a.indexOf("#");a=a.slice(d+1,e>d?e:f)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&
(d=[a]);b.each(d,function(a,b){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),c[a[0]]=a[1])});return c}return{getUrlParametersMap:d,addKeyValuePair:function(a,b,e){e=e||0;if(d(a)[b]===e||!a||!b)return a;b="?"+b+"\x3d"+e;return-1<a.indexOf("?")?a.replace("?",b+"\x26"):a+b}}});"use strict";e.when("A","cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery").register("cr-extended-uri-utils",function(b,d,a,c,e){function f(){return c(k.location.href)}function q(){return f().query()}return e.extend(d,{getCurrentUri:f,
getCurrentQueryString:q,getCurrentQueryParameters:function(){return c.parseQuery(q())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=c(b);var d=a.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=a.startsWith(b,"amazon"));return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=c(d);b.each(e,function(b,c){a.isBlank(b)?d.removeSearch(c):d=d.setSearch(c,b)});return d},setReftag:function(b,d){if("string"===
typeof b||b instanceof String)b=c(b);for(var e=b.segment(),f=!1,g=e.length-1;0<=g;g--)if(a.startsWith(e[g],"ref\x3d")){f=!0;e[g]="ref\x3d"+d;break}f||e.push("ref\x3d"+d);b.segment(e);return b}})});"use strict";e.when("A","cr-jQuery").register("histogram-trigger",function(b,d){function a(){b.onScreen(d("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});
/* ******** */
(function(c){var e=window.AmazonUIPageJS||window.P,l=e._namespace||e.attributeErrors,a=l?l("CustomerReviewsMedleyAssets",""):e;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,e,l){c.when("A","medley-twister-view","medley-twister-model","ready").register("medley-twister-controller",function(a,b,f){function c(a){a=f.getASIN();var d=b.getDisplayedASIN();d&&a!==d&&(b.fadeReviews(!0),f.getReviews(d,function(){f.setASIN(d)},function(){},function(){b.fadeReviews(!1)}))}
var g=b.getLoadedASIN();f.setASIN(g);a.on("a:pageUpdate",c);return{onTwist:c}});"use strict";c.when("A","cr-jQuery").register("medley-twister-view",function(a,b){return{getDisplayedASIN:function(){return String(b("#ASIN").val()||"")},getLoadedASIN:function(){return(b("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(a){!1===a?b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",
.5)}}});"use strict";c.when("A","cr-global-model","cr-ajax-model","cr-uri-utils","cr-jQuery").register("medley-twister-model",function(a,b,f,c,g){function h(a){var b=c.getUrlParametersMap()||{};b.asin=a;return b}var d;return{setASIN:function(a){d=a||""},getASIN:function(){return d},getReviews:function(a,b,c,d){var e=g("#cr-state-object").data("state");"string"===typeof a&&10===a.length?f.post(e.medleyReviewsAjaxUrl,{params:h(a),attribution:"getMedleyReviews",success:b,error:c,finallyCallback:d}):
"function"===typeof d&&d()}}});"use strict";c.when("A","review-skyfall-view","review-skyfall-model","reviews-constants","cr-global-view","a-button").register("review-skyfall-shared-controller",function(a,b,c,e,g,h){function d(a){a=g.getReftag(a);c.clickMetric(a,function(){})}function k(a,d){b.showMoreFeedbackSection(a.$target.closest(".cr-feedback-section"));var e=g.getReftag(a);c.clickMetric(e,a.data,function(a){d.disable()})}a.declarative(e.events.FEEDBACK_CLICK,"click",function(a){var b=h(".cr-feedback-helpful-yes, .cr-feedback-helpful-no");
k(a,b)});a.declarative(e.events.CLIQUE_CLICK,"click",d);return{feedbackClick:k,cliqueClick:d}});"use strict";c.when("A","cr-log-utils").register("review-skyfall-controller",function(a,b){a.on("a:expander:clique-ratings-read-more:toggle:expand",function(a){b.incrementCount("desktopSkyfallReadMore")});a.on("a:popover:show:skyfallWhatsThis",function(a){b.incrementCount("desktopSkyfallWhatsThis")})});"use strict";c.when("A","cr-ajax-model","cr-global-model","cr-jQuery").register("review-skyfall-model",
function(a,b,c,e){return{clickMetric:function(a,h,d){var k=e("#cr-state-object").data("state");a=c.generateUrl(k.reftagTriggerUrl,a);b.post(a,{params:h,success:d})}}});"use strict";c.when("A","reviews-constants").register("review-skyfall-view",function(a,b){return{showMoreFeedbackSection:function(a){a.find(".cr-more-feedback-section").removeClass(b.aui.HIDDEN);a.find(".cr-is-feature-helpful-row").addClass(b.aui.HIDDEN)}}})});
/* ******** */
(function(l){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsVotingAssets"):p;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,p,r){l.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(b,a,c,e){function g(a,b){k(a,b);c.showElementByCssSelector(a,b.inFlight)}function k(a,b){c.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&c.hideElementByCssSelector(a,b.hideAbuseComponents)}
function f(d,f){f.isReportAbuse&&(d=b.$("#mobile-abuse-"+f.voteInstanceId),e.get(d).hide());g(d,f.cssSelectors);a.submitVote(f.ajaxUrl,f.voteValue,f.voteInstanceId,f.csrfT,f.voteDimension,function(a){if(!0===a){a=d;var b=f.cssSelectors;k(a,b);c.showElementByCssSelector(a,b.onSuccess)}else a=d,b=f.cssSelectors,k(a,b),c.showElementByCssSelector(a,b.onError)},function(){var a=d,b=f.cssSelectors;k(a,b);c.showElementByCssSelector(a,b.onError)})}b.declarative("reviews:vote-action","click",function(a){f(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:f}});l.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,e,g,k,f,d,l){a.post(b,{params:{voteInstanceId:g,voteValue:e,csrfT:k,voteDimension:f},attribution:"submitVote",success:d,error:l})}}});l.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(b,e){a(b,e).addClass("aok-hidden")},showElementByCssSelector:function(b,e){a(b,e).removeClass("aok-hidden")}}})});
/* ******** */
(function(l){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsGalleryAssets"):p;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,p,r){l.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){l.load.css(b.reviewsLightboxCSS);var e=document.createElement("script");e.type="text/javascript";
e.async=!0;e.setAttribute("crossorigin","anonymous");e.src=b.reviewsLightboxJS;document.getElementsByTagName("head")[0].appendChild(e);a=!0;l.register("review-image-assets-loaded",{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";p.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});l.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",
function(b,a,c,e){function g(b,d,e,f,g){if(!(b&&d&&e instanceof a&&f instanceof a&&g instanceof a))return c.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+b+", galleryName: "+d+", $popoverTrigger: "+e+", $thumbnails: "+f+", $galleryLink: "+g,"FATAL"),!1;var p="reviewsLightbox-ready-"+d;f.click(function(){k(b,d);var c=f.index(this);e.click();l.when(p).execute(function(){a("#"+d).trigger("jumpToImageAtIndex",c)})});g.click(function(){k(b,d);e.click();l.when(p).execute(function(){a("#"+
d).trigger("hideImmersiveView")})});return!0}function k(a,b){if(!a||!b)return c.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+b,"FATAL"),!1;if(f)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return f=!0}var f=!1,d={};l.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),c=b.attr("data-asin");0<b.length&&c&&g(c,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),
b.find(".reviews-image-gallery-link"))});b.on(e.events.RELOAD_COMPLETE,function(){d={}});return{bindReview:function(b,c,e){var f=new ReviewGallery(e,"DESKTOP"),g=a("#"+c);g.find(".review-image-tile").each(function(c){a(this).click(function(){d[b]||(f.initializeForReview(b),d[b]=!0);g.find(".a-popover-trigger").click();l.when("reviewsLightbox-ready-"+e).execute(function(){f.render();f.showImageAtIndex(c)})})})},initializeImageGallery:k,initializeEventHandlers:g}});l.when("A","cr-jQuery",
"cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,c,e,g){function k(){b.each(a(".review-views .review"),function(a){a&&a.id&&(a=c.getEmbedInfo(a.id))&&(c.isAiryLoaded()||c.loadAssets(),e.embedVideo(a))})}b.on(g.events.RELOAD_COMPLETE,function(){k()});k();return{initAll:k}});l.when("cr-jQuery").register("cr-video-model",function(b){var a=!1;return{getEmbedInfo:function(a){var e="video-block-"+a,g=b("#"+a+" .video-url").val(),k=b("#"+a+" .video-slate-img-url").val(),
f=b("#cr-video-swf-url").val();return a&&g&&f?{videoDomId:e,videoUrl:g,videoSlateImgUrl:k,videoSwfUrl:f}:!1},isAiryLoaded:function(){return a},loadAssets:function(){var c=b("#cr-airy-js-source-url").val(),e=b("#cr-airy-css-source-url").val();"string"===typeof c&&"string"===typeof e&&(l.load.js(c),l.load.css(e));a=!0}}});l.when("cr-jQuery","afterLoad").register("cr-video-view",function(b){return{embedVideo:function(a){l.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],
slateImages:{preloadSlate:a.videoSlateImgUrl},swfUrl:a.videoSwfUrl,desiredMode:"html"})})}}})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,p=l._namespace||l.attributeErrors,d=p?p("CustomerReviewsFilteringAssets",""):l;d.guardFatal?d.guardFatal(h)(d,window):d.execute(function(){h(d,window)})})(function(h,l,p){h.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils").register("cr-filtering-controller",function(d,e,b,c,q,g,k){function h(m){var a=!1,f=!1;m.toggleFilters&&(f=!0);c.setASIN(b.getLoadedFilterParam("asin"));
a=c.setReviewerType(m.reviewerType,f)||a;a=c.setFormatType(m.formatType,f)||a;a=c.setFilterByKeyword(m.filterByKeyword,f)||a;a=c.setFilterByLanguage(m.filterByLanguage,f)||a;a=c.setSortOrder(m.sortOrder,f)||a;a=c.setStarFilter(m.filterByStar,f)||a;return a=c.setPageNumber(m.pageNumber,f)||a}function n(a){if(h(a.data)||a.data.forceReload)a.data.sortOrder&&b.setSortDropdown(a.data.sortOrder),b.hideReviewLoadError(),b.hideReviews(),b.showLoadingSpinner(),d.trigger(g.events.FILTER_APPLY_BEGIN,a),c.getReviews(function(){b.showReviews();
d.trigger(g.events.FILTER_APPLY_SUCCESS,a)},function(){b.showReviewLoadError();d.trigger(g.events.FILTER_APPLY_ERROR,a)},function(){b.hideLoadingSpinner();d.trigger(g.events.FILTER_APPLY_DONE,a);d.trigger(g.events.RELOAD_COMPLETE)},function(a){"appendFadeIn"===a[0]?k.appendFadeIn(a):"replace"===a[0]&&k.replace(a)},q.getReftag(a)),a.data.scrollToSelector&&q.scrollTo(a.data.scrollToSelector,0)}function a(a){a&&a.data&&n(a)}function f(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=
a.$target.val(),n(a))}function r(a){a&&a.data&&a.data.filterType&&(b.deactivateFilterTabHeaders(),b.activateFilterTabHeader(a.data.filterType),b.changeFilterOptionsTo(a.data.filterType))}c.setReviewsAjaxUrl(b.getReviewsAjaxUrl());d.declarative(g.events.FILTER_APPLY,"click",d.compositeEventWrapper(a,!0,100));d.declarative(g.events.FILTER_CHANGE,"change",d.compositeEventWrapper(f,!0,100));d.declarative(g.events.FILTER_TAB_CLICKED,"click",r);c.setReviewerType(b.getLoadedFilterParam("reviewerType"),!1);
c.setFormatType(b.getLoadedFilterParam("formatType"),!1);c.setFilterByKeyword(b.getLoadedFilterParam("filterByKeyword"),!1);c.setFilterByLanguage(b.getLoadedFilterParam("filterByLanguage"),!1);c.setStarFilter(b.getLoadedFilterParam("filterByStar"),!1);c.setSortOrder(b.getLoadedFilterParam("sortOrder"),!1);c.setPageNumber(b.getLoadedFilterParam("pageNumber"),!1);return{setFilterParams:h,onFilterApply:a,onFilterChange:f,onFilterTabClicked:r}});"use strict";h.when("A","cr-ajax-model","ready").register("cr-filtering-model",
function(d,e){function b(){return k.asin||""}function c(){return l||""}function h(a,f){f?k[a]=f:delete k[a]}function g(a,f,c){var b=!1;a&&f!==p&&(b=(k[a]||"")!==f,!b&&c&&(f="CLEAR_VALUE",b=!0),h(a,f));return b}var k={},l="",n;return{getReviews:function(a,f,b,c,d){var g=l;n&&e.abort(n);d&&(g+="ref\x3d"+d);n=e.post(g,{params:k,attribution:"getFilteredReviews",success:a,error:f,finallyCallback:function(){b();n=0},chunk:c})},setASIN:function(a){var c=b()!==a;h("asin",a);return c},getASIN:b,setReviewsAjaxUrl:function(a){var b=
c()!==a;l=a||"";return b},getReviewsAjaxUrl:c,setReviewerType:function(a,b){return g("reviewerType",a,b)},getReviewerType:function(){return k.reviewerType||""},setFormatType:function(a,b){return g("formatType",a,b)},getFormatType:function(){return k.formatType||""},setFilterByKeyword:function(a,b){return g("filterByKeyword",a,b)},getFilterByKeyword:function(){return k.filterByKeyword||""},setFilterByLanguage:function(a,b){return g("filterByLanguage",a,b)},getFilterByLanguage:function(){return k.filterByLanguage||
""},setSortOrder:function(a,b){return g("sortBy",a,b)},getSortOrder:function(){return k.sortBy||""},setStarFilter:function(a,b){return g("filterByStar",a,b)},getStarFilter:function(){return k.filterByStar||""},setPageNumber:function(a,b){return g("pageNumber",a,b)},getPageNumber:function(){return k.pageNumber||""},getFilterParams:function(){return k||{}},updateFilterParam:h}});"use strict";h.when("cr-A","cr-jQuery","a-dropdown","ready").register("cr-filtering-view",function(d,e,b){return{getReviewsAjaxUrl:function(){return(e("#cr-state-object").data("state")||
{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var b=d.getValueFromState("onLoadShowHideElements");e(b).removeClass("aok-hidden")},hideLoadingSpinner:function(){var b=d.getValueFromState("onLoadShowHideElements");e(b).addClass("aok-hidden")},hideReviews:function(){e(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){e(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){e(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){e(".review-load-error").addClass("aok-hidden")},
deactivateFilterTabHeaders:function(){e(".cr-tab-header-text").removeClass("cr-tab-active")},activateFilterTabHeader:function(b){e(".cr-tab-header-text-"+b).addClass("cr-tab-active")},changeFilterOptionsTo:function(b){e(".cr-tab-content").addClass("aok-hidden");e(".cr-tab-content-"+b).removeClass("aok-hidden")},getLoadedFilterParam:function(b){return(e("#cr-state-object").data("state")||{})[b]||""},setSortDropdown:function(c){b.getSelect("cm-cr-sort-dropdown").setValue(c)}}});"use strict";h.when("cr-A",
"cr-lighthut-terms-view","reviews-constants","cr-log-utils").register("cr-lighthut-terms-controller",function(d,e,b,c){function h(b){b&&b.filterByKeyword!==p&&(e.setSelected(b.filterByKeyword),c.incrementCount("LighthutTermClicked"))}d.on(b.events.FILTER_APPLY_BEGIN,d.compositeEventWrapper(function(b){b&&b.data&&h(b.data)}));return{onFilterApplied:h}});"use strict";h.when("A","cr-jQuery","ready").register("cr-lighthut-terms-view",function(d,e){return{setSelected:function(b){b=b.replace(/ /g,"_");
var c=(b=e("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");e(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");c||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
