(function(l){var p=window.AmazonUIPageJS||window.P,u=p._namespace||p.attributeErrors,f=u?u("TwisterCoreAsset",""):p;f.guardFatal?f.guardFatal(l)(f,window):f.execute(function(){l(f,window)})})(function(l,p,u){l.when("twister-variation-matrix","twister-dim-util","twister-state-machine","twister-metadata","twister-view-controller","twister-dispatcher","twister-actions","twister-slots-dimsum","twister-dimsum").register("TwisterCore",function(f,h,g,d,a,b,c,e,k){function n(c,m){this.tvm=new f(c);this.util=
new h(this.tvm);this.tsm=new g(this.tvm,this.util,c.initDimCombination);this.dimSum=new k(c.config.ajaxTimeout,c.config.ajaxUrlParams,c.config.deviceType,m);this.slotsDimSum=new e(c.config.ajaxTimeout,c.config.ajaxUrlParams,c.config.deviceType);var r=this;b.registerStore("twister-state-machine",function(b,c){r.tsm.accept(b,c).THEN(function(c){a.publishView(b,c)}).ELSE()});var t=new d;b.registerStore("twister-metadata",function(b,c){t.process(b,c,function(c){a.publishView(b,c)})})}function m(a,e){var d=
a.viewAttribution+"_"+a.viewName+"_"+e;return function(a){try{var m=c.create(e,a);b.dispatch(e,m)}catch(k){p.ueLogError&&p.ueLogError(k,{logLevel:"ERROR",attribution:"Twister_view_"+d,message:"This error is caused by the Twister view - "+d+" while updating the TwisterCore"})}}}n.prototype={registerActive:function(b,c){a.register(b.viewAttribution+"_"+b.viewName,!0,c.updateView);return{dimensionChanged:m(b,"VARIATION_CHANGE"),dimensionPeek:m(b,"VARIATION_PEEK"),metaData:m(b,"METADATA")}},registerPassive:function(b,
c){a.register(b.viewAttribution+"_"+b.viewName,!1,c.updateView);return{metaData:m(b,"METADATA")}},state:function(){return this.tsm.currentState().selected().selectionInfo()}};return n});"use strict";l.when("A").register("twister-actions",function(f){var h=f.$,g={VARIATION_CHANGE:function(d){return d=h.isArray(d)?d:[d]},VARIATION_PEEK:function(d){return d},VARIATION_SEQUENCE_ALTER:function(){},INIT_SEQUENCE_ALTER_DATA:function(d){return d},METADATA:function(d){return d}};return{create:function(d,a){return g[d]?
g[d](a):!1}}});"use strict";l.when("A","publisherSubscriber").register("twister-dispatcher",function(f,h){function g(){g=1;return this}var d=f.$,a=new h,g=0,b=[];return{registerStore:function(b,e){a.register(b,e);return this},deregisterStore:function(b){a.deRegister(b);return this},dispatch:function(c,e){g?b.push(arguments):a.publish(c,e);return this},hold:g,release:function(){d.each(b,function(b,e){a.publish.apply(a,e)});g=0;return this}}});"use strict";l.when("A","publisherSubscriber").register("twister-view-controller",
function(f,h){function g(){d?a.push(arguments):(d=1,b.publish.apply(b,arguments),c.publish.apply(c,arguments),d=0,a.length&&g.apply(this,a.shift()));return this}var d=0,a=[],b=new h,c=new h;return{register:function(a,d,n){d?b.register(a,n):c.register(a,n);return this},deRegister:function(a,d){d?b.deRegister(a):c.deRegister(a);return this},publishView:g}});"use strict";l.when("A").register("twister-dimsel-api",function(f){function h(d){var a=this;this.dimSelectionMap={};this.selInfo=d;g.each(d,function(b,
c){a.dimSelectionMap[c.dimKey]=c.val})}var g=f.$;h.prototype={matches:function(d){d=d.selectionInfo();for(var a=0;a<d.length;a++){var b=d[a].dimKey;if(!(b in this.dimSelectionMap)||this.dimSelectionMap[b]!==d[a].val)return!1}return!0},selectionInfo:function(){return f.copy(this.selInfo)}};return h});"use strict";l.when("A","twister-dimsel-api").register("twister-dim-util",function(f,h){function g(a){this.tvm=a;this.dimensionMetaData={};var b=[];a=a.dimensionInfo;for(var c=0;c<a.length;c++){b.push(a[c].dimKey);
var e={};e.isRequired=a[c].isRequired;e.isSingleton=a[c].isSingleton;e.dimOrder=c;e.size=a[c].size;this.dimensionMetaData[a[c].dimKey]=e}}var d=f.$;g.prototype={createSelectionInfo:function(a){return new h(a)},extendSelectionInfo:function(a,b,c){var e=c||0===c,k={},n=[];d.each(b.selectionInfo(),function(b,a){k[a.dimKey]=a.val});d.each(a.selectionInfo(),function(b,a){b=a.dimKey;a=e?c:a.val;b in k&&(a=k[b]);n.push({dimKey:b,val:a})});return new h(n)},createNextDimSelection:function(a,b){var c=[],e=
b.selectionInfo(),k=this;d.each(a.split(":"),function(b,a){var d=e[b].dimKey;a=parseInt(a,10);k.dimensionMetaData[d].isRequired&&a!==e[b].val&&(a=-1);c.push({dimKey:d,val:a})});return new h(c)},getDimScore:function(a,b){var c=0,e=a.split(":"),k=this;d.each(b.selectionInfo(),function(b,a){var d=a.dimKey;a=a.val;var f=parseInt(e[b],10);b=e.length-b;a===f?(c+=200*b,k.dimensionMetaData[d].isRequired&&(c+=2E4)):c+=100-Math.round(Math.abs(a-f)/k.dimensionMetaData[d].size*100)});return c},isSingletonDim:function(a){return this.dimensionMetaData[a]?
this.dimensionMetaData[a].isSingleton:!1},isRequiredDim:function(a){return this.dimensionMetaData[a]?this.dimensionMetaData[a].isRequired:!1},getDimensionInfo:function(){return this.tvm.dimensionInfo},getDimAvailability:function(a,b){b=b.selectionInfo?b:this.createSelectionInfo(b);var c=[],e=[],k=this.tvm.dimensionList,f=this.tvm.dimtoValueMap[a],m=this.createSelectionInfo([{dimKey:a,val:-1}]);b=this.tvm.fetch(this.extendSelectionInfo(b,m).selectionInfo());var g={},h=this;d.each(b,function(b,c){g[c.split(":")[k.indexOf(a)]]=
h.tvm.dimCombinations[c]});d.each(f,function(b,a){b in g?c.push({index:b,asin:g[b],label:a}):e.push({index:b,label:a})});return{available:c,unavailable:e}},getUnselectedDims:function(a){var b={};d.each(a,function(a,c){b[c.dimKey]=c.val});a=[];var c=this.tvm.dimensionList,e;for(e in c)if(c.hasOwnProperty(e)){var k=c[e];if(void 0===b[k]||-1===b[k])this.isSingletonDim(k)?b[k]=0:a.push(k)}return a},showDimSum:function(a,b){b=this.getUnselectedDims(b);return!b||0===b.length||1===b.length&&b[0]===a?1:0},
isFullySelected:function(a){var b=!0;"string"===typeof a&&(a=this.getSelectionInfoFromDimComb(a));a=a.selectionInfo?a.selectionInfo():a;if(a.length!=this.tvm.dimensionList.length)return!1;d.each(a,function(a,e){-1===e.val&&(b=!1)});return b},createDimensionSelectionMap:function(a){var b={},c;for(c in a)if(a.hasOwnProperty(c)){var e=a[c];b[e.dimKey]=e.val}return b},getSelectedDimKeys:function(a){var b=this.tvm.dimensionList,c=[],e;for(e in b)if(b.hasOwnProperty(e)){var d=a[b[e]];"undefined"===typeof d||
-1==d?c.push("*"):c.push(d)}return c},getValidDimCombination:function(a,b){var c,e=this,k=0,f=0;a=this.tvm.fetch(a);d.each(a,function(a,d){f=e.getDimScore(d,b);f>k&&(c=a,k=f)});return a[c]},getAsinFromSelectionInfo:function(a,b){var c;"undefined"==typeof b||b?a=this.createDimensionSelectionMap(a):(c=f.copy(a),a=this.getValidDimCombination(c,this.createSelectionInfo(a)),d.each(a.split(":"),function(b,a){a=parseInt(a,10);c[b].val=a}),a=this.createDimensionSelectionMap(c));a=this.getSelectedDimKeys(a).join(":");
return this.tvm.dimCombinations[a]},getSelectionInfoFromSelectedVariationValuesMap:function(a){var b=[],c;for(c in this.tvm.dimensionList){var e={},d=this.tvm.dimensionList[c];e.dimKey=d;e.val=a[d];b.push(e)}return b},getSelectionInfoFromDimComb:function(a){var b=[];a=a.split("_");for(var c in this.tvm.dimensionList){var e={},d=a[c];e.dimKey=this.tvm.dimensionList[c];e.val="X"===d||"*"===d?-1:parseInt(d,10);b.push(e)}return b},getDimensionDisplayText:function(a){return this.tvm.dimensionDisplayText[a]},
getDimensionValueFromIndex:function(a,b){return(this.tvm.dimtoValueMap[a]||[])[b]},getSelectionInfoFromDimIndexAndValue:function(a,b){var c=[],d={};d.dimKey=this.tvm.dimensionList[a];d.val="X"===b||"*"===b?-1:parseInt(b,10);c.push(d);return c},predictNextState:function(a,b){var c=this.extendSelectionInfo(a,b);if(function(b){var a;d.each(b.selectionInfo(),function(b,c){a=-1===c.val});return a}(b)||this.tvm.exists(c.selectionInfo()))return c;a=this.extendSelectionInfo(a,b,-1);a=this.tvm.fetch(a.selectionInfo());
for(var e=b=0,f,g=0;g<a.length;g++)e=this.getDimScore(a[g],c),e>b&&(f=g,b=e);return this.createNextDimSelection(a[f],c)},getAsinToCorrespondingDimensionIndexMap:function(a){var b={};d.each(this.tvm.dimCombinations,function(c,d){b[d]=parseInt(c.split(":")[a-1])});return b}};return g});"use strict";l.when("A","url-builder").register("twister-dimsum",function(f,h){function g(a,b,c,d){this.cache;d&&(this.cache=new d);this.ajaxTimeout=a;this.batchLimit=10;this.ajaxUrl="/gp/twister/dimension?asinList\x3d###asinString###\x26vs\x3d1"+
(b||"");c&&(this.ajaxUrl+="\x26deviceType\x3d"+c);(a=f.state("pwState"))&&a.isTryState&&(this.ajaxUrl=h.addUrlParams(this.ajaxUrl,{isTryState:"true"}))}var d=f.$;g.prototype={get:function(a,b,c){function e(b){var a=b-this.batchLimit;0<a&&e.call(this,a);if(b=q.slice(0>a?0:a,b).join(","))b=this.ajaxUrl.replace("###asinString###",b),f.ajax(b,{chunk:g,timeout:this.ajaxTimeout})}function g(a){if(a)for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(e&&e.asin){if(m){var f=h(e.asin,c);m.put(f,e)}b&&b(e)}}}
function h(b,a){var c=b;f.objectIsEmpty(a)||(c={asin:b},d.extend(!0,c,a));return c}var m=this.cache,q=[],l={};d.each(a,function(a,d){a=h(d,c);m&&m.get(a)?b?b(m.get(a)):l[d]=m.get(a):q.push(d)});if(!b)return l;e.call(this,q.length)}};return g});"use strict";l.when("A").register("twister-slots-dimsum",function(f){function h(a,c,e){this.cache=d;this.ajaxTimeout=a;this.batchLimit=8;this.ajaxUrl="/gp/twister/dimension?isDimensionSlotsAjax\x3d1\x26asinList\x3d###asinString###\x26vs\x3d1"+(c||"");e&&(this.ajaxUrl+=
"\x26deviceType\x3d"+e);this.defaultQuerryParamsObj={};this.defaultAddedQueryParamString=""}var g=f.$,d={},a={};h.prototype={get:function(b,c){function d(a){var b=a-this.batchLimit;0<b&&d.call(this,b);a=q.slice(0>b?0:b,a);if(b=a.join(","))b=this.ajaxUrl.replace("###asinString###",b),b+="\x26"+this.defaultAddedQueryParamString,f.ajax(b,{chunk:h,timeout:this.ajaxTimeout,cache:!0,error:k.apply(null,a)})}function k(){var b=arguments;return function(){f.each(b,function(b){delete a[b]})}}function h(b){if(b&&
b.ASIN){var d=b.ASIN;m[d]=b;for(c&&c(b);a[d]&&a[d].length;)a[d].pop()(b);delete a[d]}}var m=this.cache,q=[],l={};g.each(b,function(b,d){m[d]?c?c(m[d]):l[d]=m[d]:a[d]&&c?a[d].push(c):c&&(q.push(d),a[d]=[])});if(!c)return l;q.length&&d.call(this,q.length)},addDefaultQueryParameter:function(b,a){var d=!1;void 0!==a&&(this.defaultQuerryParamsObj[b]=a,this.defaultAddedQueryParamString=g.param(this.defaultQuerryParamsObj),d=!0);return d},getBatchSize:function(){return 8}};return h});"use strict";l.register("twister-metadata",
function(){function f(){this.config={}}f.prototype={process:function(f,g,d){"METADATA"===f&&d(g)}};return f});"use strict";l.when("A").register("publisherSubscriber",function(f){function h(){this.Subscribers=[];this.Names=[]}var g=f.$;h.prototype={register:function(d,a){if(-1<f.indexOfArray(this.Names,d))return!1;this.Names.push(d);this.Subscribers.push({name:d,handler:a})},deRegister:function(d){var a=f.indexOfArray(this.Names,d),b=this,c=function(a,c){if(a.name===d)return b.Subscribers.splice(c,
1),!0};return-1<a?(this.Names.splice(a,1),[].some?this.Subscribers.some(c):g.each(this.Subscribers,function(b,a){c(a,b)}),!0):!1},publish:function(){var d=arguments;g.each(this.Subscribers,function(a,b){setTimeout(function(){b.handler.apply(null,d)},0)})}};return h});"use strict";l.when("jQuery","twister-core-store-utils").register("twister-state-machine",function(f,h){return function(f,d,a){function b(b,a){this.selected=function(){return b};this.peek=function(){return a}}function c(a){var c=d.createSelectionInfo(a),
e=k();if(e.peek().matches(c))return!1;if(-1===a.val)return n=e=new b(k.selected(),k.selected()),!0;a=d.predictNextState(e.peek(),c);n=e=new b(e.selected(),a);return!0}function e(a){var c=k();a=d.createSelectionInfo(a);var e=d.getDimensionInfo();if(c.selected().matches(a))return!1;c=a.selectionInfo().length!==e.length?d.predictNextState(c.selected(),a):a;n=new b(c,c);return!0}var k,n;this.StoreUtils=h;this.accept=function(a,b){switch(a){case "VARIATION_PEEK":a=this.StoreUtils.branch(c(b),this.currentState);
break;case "VARIATION_CHANGE":a=this.StoreUtils.branch(e(b),this.currentState);break;default:a=this.StoreUtils.branch(!1)}return a};k=this.currentState=function(){return n};n=new b(d.createSelectionInfo(a),d.createSelectionInfo(a))}});"use strict";l.register("twister-core-store-utils",function(f){return{branch:function(f,g){return{THEN:function(d){if(f&&d){var a=g?g():f;d(a)}return this},ELSE:function(d){if(!f&&d){var a=g?g():f;d(a)}return this}}}}});"use strict";l.when("A","twister-core-store-utils").register("variation-sequence-alter",
function(f,h){return function(g){function d(a,b){var c=a[0],d=b[0];a=a[1];b=b[1];return a===b?r[c]-r[d]:a-b}function a(){if(m)return!0;var a=[];r=g.getAsinToCorrespondingDimensionIndexMap(n);f.each(l,function(b,c){b.sort(d);a=a.concat(b)});var b=c(a);m=p=e(r,b);return!0}function b(a){var b=!1;t||(b=a?a.asinToOfferInfoMap:void 0,n=a?a.slotRowNumber:void 0,b=b&&n?(l=k(b))?!0:!1:!1,t=b);return b}function c(a){var b={};f.each(a,function(a,c){b[a[0]]=c});return b}function e(a,b){var c=[];f.each(a,function(a,
d){c.push([a,b[d]])});return c}function k(a){var b={};f.each(a,function(a,c){var d=a.split(":");a=d[0];d=d[1];b[a]=b[a]?b[a]:[];b[a].push([c,d])});return b}var n,m,l={},p,r,t=!1;this.StoreUtils=h;this.accept=function(c,d){switch(c){case "VARIATION_SEQUENCE_ALTER":c=this.StoreUtils.branch(a(d),this.getAlteredIndicesMap);break;case "INIT_SEQUENCE_ALTER_DATA":c=this.StoreUtils.branch(b(d));break;default:c=this.StoreUtils.branch(!1)}return c};this.getAlteredIndicesMap=function(){return m}}});"use strict";
l.when("A").register("twister-variation-matrix",function(f){function h(b){b=f.copy(b);var c=this;this.dimCombinations=b.dimCombinations;this.validCombinatonString=" "+f.keys(b.dimCombinations).join("  ")+" ";this.dimensionInfo=b.dimensionInfo;this.dimensionList=b.dimensionList;this.dimensionDisplayText=b.dimensionDisplayText;this.config=b.config;this.dimInfoMap={};a.each(this.dimensionInfo,function(a,b){var d=b.dimKey,f={};f.size=b.size;f.dimOrder=a;c.dimInfoMap[d]=f});this.dimtoValueMap=b.dimtoValueMap}
function g(b){b=a.map(b,function(a){a=a.val;return-1===a?"\\d+":""+a}).join(":");return new RegExp("\\s"+b+"\\s","gm")}function d(b){return a.map(b,function(a){return""+a.val}).join(":")}var a=f.$;h.prototype={fetch:function(b){b=g(b);b=this.validCombinatonString.match(b);return b=a.map(b,function(b){return a.trim(b)})},exists:function(a){return d(a)in this.dimCombinations}};return h});"use strict";l.when("A","jQuery").register("url-builder",function(f,h){function g(a,c){var d;if(a&&c&&"object"==
typeof c){d=a;var g="?";f.each(c,function(a,b){a=c[b];d+=g+b+"\x3d"+a;g="\x26"})}return d}function d(a){var c;a&&(c=a.split("?")[0]);return c}function a(a){var c={};a&&(a=a.split("?"),1<a.length&&(a=a[1].split("\x26"),f.each(a,function(a,b){a=a.split("\x3d");c[a[0]]=a[1]})));return c}return{addUrlParams:function(b,c){var e=b;b&&c&&"object"==typeof c&&(e=d(b),b=a(b),b=h.extend(b,c),e=g(e,b));return e},removeUrlParams:function(b,c){var e=b;if(b&&c&&"object"==typeof c){var e=d(b),h=a(b);f.each(c,function(a,
b){delete h[a]});e=g(e,h)}return e}}})});